export interface BusinessData {
    id: number;
    user_id: number;
    name: string;
    type: string | null;
    industry_id: number | null;
    description: string | null;
    class: string | null;
    tin: string | null;
    logo: string | null;
    account: string;
    biz_email: string | null;
    biz_bvn: string | null;
    biz_phone: string | null;
    biz_url: string | null;
    biz_country: string | null;
    biz_state: string | null;
    biz_city: string | null;
    biz_address: string | null;
    rcNumber: string | null;
    incorporationDate: string | null;
    d_bvn: string | null;
    id_means: string | null;
    id_number: string | null;
    id_holder: string | null;
    d_bvn2: string | null;
    id_means2: string | null;
    id_number2: string | null;
    id_holder2: string | null;
    chargeback_email: string | null;
    acc_prefix: string;
    profile_completed: number;
    kyc_submitted: number;
    kyc_level: number;
    settlement_day: number;
    settlement_type: string;
    instant_settlement: string;
    collection_fee: string;
    collection_cent: string;
    collection_cent_cap: string;
    checkout_fee_type: string;
    checkout_flat: string;
    checkout_cent: string;
    checkout_cent_cap: string;
    sh_fee_type: string;
    sh_flat_fee: string;
    sh_cent: string;
    sh_cent_cap: string;
    feeBearer: string;
    payout_fee: string;
    split_payment_fee: string;
    bvn_fee: string;
    mode: string;
    email_alert: number;
    customer_email_alert: number;
    trans_pin: string;
    collection_status: number;
    bills_status: number;
    payout_status: number;
    payout_limit_per_trans: string;
    daily_trans_limit: string;
    note: string | null;
    rm: number;
    status: string;
    created_at: string;
    updated_at: string;
}